"""Shared plugin-root references vendored into citing skills (P33).

A skill declares shared references in a fenced ``harness-kit-shared-references``
block in its SKILL.md and cites them as ``references/_shared/<name>.md``; the
generator copies ``plugins/<plugin>/references/<name>.md`` to
``plugins/<plugin>/skills/<skill>/references/_shared/<name>.md`` rendered as
``banner(repo-relative source path) + source bytes``.
"""

from pathlib import Path

import pytest

from harness_kit import manifests

HARNESS_TOML = (
    "[marketplace]\n"
    'name = "demo-harness"\n'
    'description = "demo marketplace"\n'
    'version = "0.1.0"\n'
    "[marketplace.owner]\n"
    'name = "A"\n'
    'email = "a@example.com"\n'
)

TRIAGE_SRC = "# Context triage\n\nDo the triage.\n"


def _skill_md(
    name: str,
    *,
    declare: tuple[str, ...] = ("context-triage.md",),
    cite: tuple[str, ...] = ("context-triage.md",),
) -> str:
    cites = "".join(f"Read `references/_shared/{c}` first.\n" for c in cite)
    block = ""
    if declare:
        entries = "".join(f"{d}\n" for d in declare)
        block = f"```harness-kit-shared-references\n{entries}```\n"
    return f"---\nname: {name}\ndescription: {name}\n---\n\n{cites}\n{block}"


def _shared_repo(
    root: Path,
    *,
    sources: dict[str, str] | None = None,
    skill_md: str | None = None,
    meta_extra: str = "",
) -> Path:
    """A repo with one plugin ``demo`` and one skill ``one``. Returns the plugin dir."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "harness.toml").write_text(HARNESS_TOML)
    pdir = root / "plugins" / "demo"
    refs = pdir / "references"
    refs.mkdir(parents=True, exist_ok=True)
    for fname, body in (
        sources if sources is not None else {"context-triage.md": TRIAGE_SRC}
    ).items():
        (refs / fname).write_text(body)
    (pdir / "plugin.meta.toml").write_text(
        'name="demo"\nversion="0.1.0"\ndescription="d"\nauthor="A"\nkeywords=["x"]\n' + meta_extra
    )
    sd = pdir / "skills" / "one"
    sd.mkdir(parents=True, exist_ok=True)
    (sd / "SKILL.md").write_text(skill_md if skill_md is not None else _skill_md("one"))
    return pdir


def _dest(pdir: Path, name: str = "context-triage.md", skill: str = "one") -> Path:
    return pdir / "skills" / skill / "references" / "_shared" / name


def test_generates_declared_shared_reference_with_banner(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    assert manifests.write_all(tmp_path)  # changed
    dest = _dest(pdir)
    text = dest.read_text()
    banner, blank, body = text.split("\n", 2)
    assert banner.startswith("<!-- GENERATED by harness-kit from ")
    assert "plugins/demo/references/context-triage.md" in banner  # repo-relative, POSIX
    assert str(tmp_path) not in banner  # never an absolute checkout path
    assert blank == ""  # banner separated from content by a blank line
    assert body == TRIAGE_SRC  # source bytes verbatim after the banner
    assert not manifests.write_all(tmp_path)  # idempotent


def test_check_detects_missing_shared_copy_without_writing(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)  # everything generated and clean
    _dest(pdir).unlink()
    assert manifests.write_all(tmp_path, dry_run=True)  # check fails: copy missing
    assert not _dest(pdir).exists()  # dry-run wrote nothing back


def test_stale_shared_copy_fails_check_and_is_regenerated(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    rendered = _dest(pdir).read_text()
    _dest(pdir).write_text(rendered + "hand edit\n")
    assert manifests.write_all(tmp_path, dry_run=True)  # check fails on drift
    manifests.write_all(tmp_path)
    assert _dest(pdir).read_text() == rendered  # gen repaired it


def test_source_change_propagates(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    (pdir / "references" / "context-triage.md").write_text("# v2\n")
    assert manifests.write_all(tmp_path, dry_run=True)  # copy now stale vs source
    manifests.write_all(tmp_path)
    assert _dest(pdir).read_text().endswith("# v2\n")


def test_no_declaration_block_no_copy(tmp_path: Path):
    pdir = _shared_repo(tmp_path, skill_md="---\nname: one\ndescription: d\n---\n\nplain skill\n")
    manifests.write_all(tmp_path)
    assert not (pdir / "skills" / "one" / "references").exists()


# --- T09: declaration-entry validation ---------------------------------------


def test_traversal_entry_rejected(tmp_path: Path):
    _shared_repo(tmp_path, skill_md=_skill_md("one", declare=("../secret.md",), cite=()))
    with pytest.raises(ValueError, match="not a plugin-root basename"):
        manifests.write_all(tmp_path)


def test_path_entry_rejected(tmp_path: Path):
    _shared_repo(tmp_path, skill_md=_skill_md("one", declare=("sub/context-triage.md",), cite=()))
    with pytest.raises(ValueError, match="not a plugin-root basename"):
        manifests.write_all(tmp_path)


def test_non_markdown_entry_rejected(tmp_path: Path):
    _shared_repo(tmp_path, skill_md=_skill_md("one", declare=("context-triage",), cite=()))
    with pytest.raises(ValueError, match="not a plugin-root basename"):
        manifests.write_all(tmp_path)


def test_duplicate_entry_rejected(tmp_path: Path):
    _shared_repo(
        tmp_path,
        skill_md=_skill_md("one", declare=("context-triage.md", "context-triage.md")),
    )
    with pytest.raises(ValueError, match="duplicate"):
        manifests.write_all(tmp_path)


def test_typoed_entry_with_no_source_rejected(tmp_path: Path):
    _shared_repo(
        tmp_path,
        skill_md=_skill_md("one", declare=("context-triag.md",), cite=("context-triag.md",)),
    )
    with pytest.raises(ValueError, match="no plugin-root reference"):
        manifests.write_all(tmp_path)


def test_case_mismatched_entry_rejected_even_on_case_insensitive_fs(tmp_path: Path):
    _shared_repo(
        tmp_path,
        skill_md=_skill_md("one", declare=("Context-Triage.md",), cite=("Context-Triage.md",)),
    )
    with pytest.raises(ValueError, match="exact-case"):
        manifests.write_all(tmp_path)


def test_case_mismatched_source_file_rejected_even_on_case_insensitive_fs(tmp_path: Path):
    # Mirror image of the mismatch above: here the entry/citation are correctly
    # cased and the plugin-root SOURCE file on disk is the one mis-cased. The
    # directory listing in `_declared_shared_refs` reflects the real on-disk
    # name regardless of the filesystem's own case sensitivity, so this must
    # reject exactly like a mis-cased declaration does.
    _shared_repo(tmp_path, sources={"Context-Triage.md": TRIAGE_SRC})
    with pytest.raises(ValueError, match="exact-case"):
        manifests.write_all(tmp_path)


def test_case_mismatched_citation_rejected(tmp_path: Path):
    # SKILL.md declares the correctly-cased entry but cites a mis-cased path;
    # the mis-cased citation itself was never declared, so this is caught by
    # the cited-but-undeclared check, not the exact-case check above.
    _shared_repo(
        tmp_path,
        skill_md=_skill_md("one", declare=("context-triage.md",), cite=("Context-Triage.md",)),
    )
    with pytest.raises(ValueError, match="not declared"):
        manifests.write_all(tmp_path)


def test_declared_but_never_cited_rejected(tmp_path: Path):
    _shared_repo(tmp_path, skill_md=_skill_md("one", declare=("context-triage.md",), cite=()))
    with pytest.raises(ValueError, match="never cited"):
        manifests.write_all(tmp_path)


def test_cited_but_undeclared_rejected(tmp_path: Path):
    _shared_repo(tmp_path, skill_md=_skill_md("one", declare=(), cite=("context-triage.md",)))
    with pytest.raises(ValueError, match="not declared"):
        manifests.write_all(tmp_path)


def test_placeholder_citation_in_prose_is_ignored(tmp_path: Path):
    md = _skill_md("one") + "\nExample form: `references/_shared/<name>.md` (placeholder).\n"
    _shared_repo(tmp_path, skill_md=md)
    manifests.write_all(tmp_path)  # must not raise: <name> is not an operational citation


# --- T07: refuse self-locating sources ---------------------------------------


def test_source_containing_escape_path_refused(tmp_path: Path):
    _shared_repo(
        tmp_path,
        sources={"context-triage.md": "Read this as `../../references/context-triage.md`.\n"},
    )
    with pytest.raises(ValueError, match=r"\.\./\.\./references/"):
        manifests.write_all(tmp_path)


# --- T10: [generated_shared_references] schema validation ---------------------


def test_meta_opt_out_parsed(tmp_path: Path):
    pdir = _shared_repo(
        tmp_path, meta_extra="[generated_shared_references]\ncheck_freshness = false\n"
    )
    meta = manifests.load_meta(pdir / "plugin.meta.toml")
    assert meta.generated_shared_references == {"check_freshness": False}


def test_meta_unknown_key_in_opt_out_table_rejected(tmp_path: Path):
    pdir = _shared_repo(
        tmp_path, meta_extra="[generated_shared_references]\ncheck_freshnes = false\n"
    )
    with pytest.raises(ValueError, match="check_freshnes"):
        manifests.load_meta(pdir / "plugin.meta.toml")


def test_meta_wrong_type_rejected(tmp_path: Path):
    pdir = _shared_repo(
        tmp_path, meta_extra='[generated_shared_references]\ncheck_freshness = "no"\n'
    )
    with pytest.raises(ValueError, match="check_freshness"):
        manifests.load_meta(pdir / "plugin.meta.toml")


def test_meta_typoed_table_rejected(tmp_path: Path):
    pdir = _shared_repo(
        tmp_path, meta_extra="[generated_shared_reference]\ncheck_freshness = false\n"
    )
    with pytest.raises(ValueError, match="generated_shared_reference"):
        manifests.load_meta(pdir / "plugin.meta.toml")


# --- T04: per-plugin freshness opt-out ---------------------------------------

OPT_OUT = "[generated_shared_references]\ncheck_freshness = false\n"


def test_opt_out_masks_staleness_in_check(tmp_path: Path):
    pdir = _shared_repo(tmp_path, meta_extra=OPT_OUT)
    manifests.write_all(tmp_path)
    _dest(pdir).write_text(_dest(pdir).read_text() + "hand edit\n")
    assert not manifests.write_all(tmp_path, dry_run=True)  # staleness masked


def test_opt_out_never_masks_missing_destination(tmp_path: Path):
    pdir = _shared_repo(tmp_path, meta_extra=OPT_OUT)
    manifests.write_all(tmp_path)
    _dest(pdir).unlink()
    assert manifests.write_all(tmp_path, dry_run=True)  # absence always fails check


def test_opt_out_gen_still_regenerates(tmp_path: Path):
    pdir = _shared_repo(tmp_path, meta_extra=OPT_OUT)
    manifests.write_all(tmp_path)
    rendered = _dest(pdir).read_text()
    _dest(pdir).write_text(rendered + "hand edit\n")
    manifests.write_all(tmp_path)  # write mode ignores the flag
    assert _dest(pdir).read_text() == rendered


def test_opt_out_toggle_never_changes_generated_set(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    rendered = _dest(pdir).read_text()
    meta = pdir / "plugin.meta.toml"
    meta.write_text(meta.read_text() + OPT_OUT)  # opt out AFTER generating
    assert not manifests.write_all(tmp_path)  # toggling generates/prunes nothing
    assert _dest(pdir).read_text() == rendered


# --- T08: orphan pruning, scoped to banner-owned copies ----------------------

PLAIN_SKILL = "---\nname: one\ndescription: d\n---\n\nplain skill\n"


def test_orphan_reported_by_check_then_pruned_by_gen(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    (pdir / "skills" / "one" / "SKILL.md").write_text(PLAIN_SKILL)  # citation removed
    assert manifests.write_all(tmp_path, dry_run=True)  # check REPORTS the orphan
    assert _dest(pdir).exists()  # ...without deleting it
    manifests.write_all(tmp_path)
    assert not _dest(pdir).exists()  # gen prunes the proven orphan
    assert not _dest(pdir).parent.exists()  # empty _shared dir removed too
    assert not manifests.write_all(tmp_path)  # now clean


def test_prune_leaves_non_banner_files_alone(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    stray = _dest(pdir).parent / "notes.md"
    stray.write_text("my scratch notes\n")  # no banner: not ours to delete
    assert not manifests.write_all(tmp_path)
    assert stray.read_text() == "my scratch notes\n"


def test_deleted_skill_md_leaves_prunable_orphan(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    (pdir / "skills" / "one" / "SKILL.md").unlink()
    assert manifests.write_all(tmp_path, dry_run=True)
    manifests.write_all(tmp_path)
    assert not _dest(pdir).exists()


def test_missing_source_with_live_declaration_errors_and_preserves_destination(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    (pdir / "references" / "context-triage.md").unlink()  # source renamed/removed
    with pytest.raises(ValueError, match="no plugin-root reference"):
        manifests.write_all(tmp_path)
    assert _dest(pdir).exists()  # declared copy preserved, never pruned


# --- T03/T19: check mode names each failing destination ----------------------


def test_check_names_missing_destination(tmp_path: Path, capsys):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    _dest(pdir).unlink()
    manifests.write_all(tmp_path, dry_run=True)
    err = capsys.readouterr().err
    assert "missing generated reference" in err
    assert "plugins/demo/skills/one/references/_shared/context-triage.md" in err


def test_check_names_stale_destination(tmp_path: Path, capsys):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    _dest(pdir).write_text(_dest(pdir).read_text() + "edit\n")
    manifests.write_all(tmp_path, dry_run=True)
    err = capsys.readouterr().err
    assert "stale generated reference" in err
    assert "plugins/demo/skills/one/references/_shared/context-triage.md" in err


def test_check_names_orphaned_destination(tmp_path: Path, capsys):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    (pdir / "skills" / "one" / "SKILL.md").write_text(PLAIN_SKILL)
    manifests.write_all(tmp_path, dry_run=True)
    err = capsys.readouterr().err
    assert "orphaned generated reference" in err
    assert "plugins/demo/skills/one/references/_shared/context-triage.md" in err


def test_case_mismatched_destination_fails_check(tmp_path: Path, capsys):
    # P33-TS05: the destination itself gets renamed to the wrong case on disk
    # (simulating a mis-cased copy slipping past on a case-insensitive
    # filesystem). Rename via a temp name first — a same-name case-only
    # rename is a no-op on case-insensitive macOS unless routed through an
    # intermediate name. Check mode must still fail: the orphan sweep lists
    # the real (mis-cased) directory entry and compares it by exact Path
    # identity against the expected (correctly-cased) destination, so the
    # mismatch is reported as an orphan regardless of the filesystem's own
    # case sensitivity.
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    dest = _dest(pdir)
    tmp_name = dest.with_name("context-triage.md.tmp")
    dest.rename(tmp_name)
    tmp_name.rename(dest.with_name("Context-Triage.md"))
    assert manifests.write_all(
        tmp_path, dry_run=True
    )  # check fails on the case-mismatched destination
    err = capsys.readouterr().err
    assert "orphaned generated reference" in err
    assert "plugins/demo/skills/one/references/_shared/Context-Triage.md" in err


def test_write_mode_and_clean_check_stay_silent(tmp_path: Path, capsys):
    _shared_repo(tmp_path)
    manifests.write_all(tmp_path)  # write mode: silent
    manifests.write_all(tmp_path, dry_run=True)  # clean check: silent
    out = capsys.readouterr()
    assert out.err == "" and out.out == ""


# --- byte fidelity (PR #3 review) --------------------------------------------


def test_crlf_source_bytes_preserved_verbatim(tmp_path: Path):
    src_body = "# Title\r\nline two\r\n"
    pdir = _shared_repo(tmp_path, sources={"context-triage.md": src_body})
    manifests.write_all(tmp_path)
    raw = _dest(pdir).read_bytes()
    assert raw.endswith(src_body.encode())  # CRLF survives vendoring byte-for-byte
    assert not manifests.write_all(tmp_path, dry_run=True)  # and stays clean


def test_prune_leaves_undecodable_stray_binary_alone(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    stray = _dest(pdir).parent / "image.md"
    stray.write_bytes(b"\xff\xfe\x00binary")
    assert not manifests.write_all(tmp_path)  # no crash, nothing changed
    assert stray.read_bytes() == b"\xff\xfe\x00binary"  # stray untouched


# --- symlink confinement + scalar meta (PR #3 review, greptile P1s) ----------


def test_symlinked_source_rejected(tmp_path: Path):
    outside = tmp_path / "outside.md"
    outside.write_text("secret bytes from outside the plugin\n")
    pdir = _shared_repo(tmp_path)
    ref = pdir / "references" / "context-triage.md"
    ref.unlink()
    ref.symlink_to(outside)
    with pytest.raises(ValueError, match="symlink"):
        manifests.write_all(tmp_path)


def test_symlinked_destination_replaced_not_followed(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    rendered = _dest(pdir).read_bytes()
    victim = tmp_path / "victim.md"
    victim.write_text("precious external content\n")
    _dest(pdir).unlink()
    _dest(pdir).symlink_to(victim)
    manifests.write_all(tmp_path)
    assert victim.read_text() == "precious external content\n"  # never written through
    assert not _dest(pdir).is_symlink()  # link replaced by a real file
    assert _dest(pdir).read_bytes() == rendered


def test_check_flags_symlinked_destination(tmp_path: Path):
    pdir = _shared_repo(tmp_path)
    manifests.write_all(tmp_path)
    twin = tmp_path / "twin.md"
    twin.write_bytes(_dest(pdir).read_bytes())  # byte-identical target
    _dest(pdir).unlink()
    _dest(pdir).symlink_to(twin)
    assert manifests.write_all(tmp_path, dry_run=True)  # a symlink is never a valid copy


def test_meta_scalar_generated_shared_references_rejected(tmp_path: Path):
    pdir = _shared_repo(tmp_path, meta_extra="generated_shared_references = true\n")
    with pytest.raises(ValueError, match="table"):
        manifests.load_meta(pdir / "plugin.meta.toml")


def test_symlinked_parent_dir_rejected(tmp_path: Path):
    outside = tmp_path / "outside-dir"
    outside.mkdir()
    pdir = _shared_repo(tmp_path)
    (pdir / "skills" / "one" / "references").symlink_to(outside)
    with pytest.raises(ValueError, match="outside the skill"):
        manifests.write_all(tmp_path)
    assert list(outside.iterdir()) == []  # nothing was written through the link


def test_prune_never_deletes_through_symlinked_shared_dir(tmp_path: Path):
    outside = tmp_path / "outside-dir"
    outside.mkdir()
    victim = outside / "victim.md"
    victim.write_bytes(b"<!-- GENERATED by harness-kit from x.md -- -->\n\nnot ours\n")
    pdir = _shared_repo(tmp_path, skill_md=PLAIN_SKILL)
    refs = pdir / "skills" / "one" / "references"
    refs.mkdir()
    (refs / "_shared").symlink_to(outside)
    manifests.write_all(tmp_path)
    assert victim.exists()  # the sweep never deletes through a symlinked _shared


def test_symlinked_references_root_rejected(tmp_path: Path):
    outside = tmp_path.parent / f"{tmp_path.name}-ext"
    outside.mkdir()
    (outside / "context-triage.md").write_text("external secret\n")
    pdir = _shared_repo(tmp_path, sources={})
    refs = pdir / "references"
    refs.rmdir()
    refs.symlink_to(outside)
    with pytest.raises(ValueError, match="references directory"):
        manifests.write_all(tmp_path)


def test_symlinked_skill_root_rejected(tmp_path: Path):
    outside = tmp_path.parent / f"{tmp_path.name}-ext2"
    (outside / "references").mkdir(parents=True)
    (outside / "SKILL.md").write_text(_skill_md("two"))
    pdir = _shared_repo(tmp_path, skill_md=PLAIN_SKILL)
    (pdir / "skills" / "two").symlink_to(outside)
    with pytest.raises(ValueError, match="skill directory"):
        manifests.write_all(tmp_path)
    assert not (outside / "references" / "_shared").exists()  # nothing written externally


def test_prune_never_sweeps_through_symlinked_skill_dir(tmp_path: Path):
    outside = tmp_path.parent / f"{tmp_path.name}-ext3"
    shared = outside / "references" / "_shared"
    shared.mkdir(parents=True)
    victim = shared / "victim.md"
    victim.write_bytes(b"<!-- GENERATED by harness-kit from x.md -- -->\n\nexternal\n")
    pdir = _shared_repo(tmp_path)
    (pdir / "skills" / "two").symlink_to(outside)  # no SKILL.md discovery guard fires: none exists
    manifests.write_all(tmp_path)
    assert victim.exists()  # sweep must never delete outside the repository
