"""Generate Claude + Codex plugin manifests from a single source of truth.

Each plugin owns one ``plugin.meta.toml``; each harness repo owns one
``harness.toml`` describing the marketplace. From these we render:

- the repo-level Claude ``.claude-plugin/marketplace.json`` (lists all plugins),
- each plugin's ``.claude-plugin/plugin.json``,
- each plugin's ``.codex-plugin/plugin.json``.

Per-plugin manifests carry a ``_generated`` marker; the repo-level
``marketplace.json`` is regenerated wholesale (no marker). All generated files
are byte-stable, and a regenerate-and-diff check (``--check``) guarantees they
never drift — including a sweep that prunes orphaned vendored code when a plugin
drops its ``[vendor]`` table or renames its skill.

Extracted and generalized from ``smorin-harness`` so the generator is shared,
never copied. The marketplace identity (name/owner/metadata) is parameterized via
``harness.toml`` instead of being hard-coded to one repo.
"""

from __future__ import annotations

import json
import shutil
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

_GEN_NOTE = "GENERATED by harness-kit from plugin.meta.toml / harness.toml — do not edit"


@dataclass(frozen=True)
class PluginMeta:
    name: str
    version: str
    description: str
    author: str = ""
    keywords: list[str] = field(default_factory=list)
    interface: dict = field(default_factory=dict)
    vendor: dict = field(default_factory=dict)
    path: Path | None = None


@dataclass(frozen=True)
class MarketplaceMeta:
    name: str
    description: str
    version: str
    owner: dict = field(default_factory=dict)
    vendor_namespace: str = ""


def load_meta(meta_path: Path) -> PluginMeta:
    data = tomllib.loads(meta_path.read_text())
    return PluginMeta(
        name=data["name"],
        version=data["version"],
        description=data["description"],
        author=data.get("author", ""),
        keywords=list(data.get("keywords", [])),
        interface=dict(data.get("interface", {})),
        vendor=dict(data.get("vendor", {})),
        path=meta_path.parent,
    )


def load_marketplace_meta(root: Path) -> MarketplaceMeta:
    data = tomllib.loads((root / "harness.toml").read_text())
    m = data["marketplace"]
    return MarketplaceMeta(
        name=m["name"],
        description=m["description"],
        version=m["version"],
        owner=dict(m.get("owner", {})),
        vendor_namespace=m.get("vendor_namespace", ""),
    )


def render_claude_plugin(m: PluginMeta) -> dict:
    return {
        "_generated": _GEN_NOTE,
        "name": m.name,
        "version": m.version,
        "description": m.description,
        "author": m.author,
        "keywords": m.keywords,
    }


def render_codex_plugin(m: PluginMeta) -> dict:
    interface = {
        "displayName": m.name.replace("-", " ").title(),
        "shortDescription": m.description,
        "longDescription": m.description,
        "category": "Developer Tools",
    }
    interface.update(m.interface)
    return {
        "_generated": _GEN_NOTE,
        "name": m.name,
        "version": m.version,
        "description": m.description,
        "skills": "./skills/",
        "interface": interface,
    }


def render_marketplace(metas: list[PluginMeta], mkt: MarketplaceMeta) -> dict:
    return {
        "name": mkt.name,
        "owner": mkt.owner,
        "metadata": {"description": mkt.description, "version": mkt.version},
        "plugins": [
            {
                "name": m.name,
                "source": f"./plugins/{m.name}",
                "description": m.description,
                "version": m.version,
                "author": m.author,
                "keywords": m.keywords,
            }
            for m in metas
        ],
    }


def _discover(root: Path) -> list[PluginMeta]:
    return [load_meta(p) for p in sorted((root / "plugins").glob("*/plugin.meta.toml"))]


def _dumps(obj: dict) -> str:
    return json.dumps(obj, indent=2) + "\n"


def _write_if_changed(path: Path, content: str, *, dry_run: bool) -> bool:
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return False
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return True


_VENDOR_INIT = '"""Vendored copy — generated by harness-kit; do not edit."""\n'


def _vendor_dir(m: PluginMeta, namespace: str) -> Path:
    """The ``_vendor/<namespace>`` dir a ``[vendor]`` plugin owns."""
    assert m.path is not None
    return m.path / "skills" / m.vendor["skill"] / "scripts" / "_vendor" / namespace


def vendor_plugin(root: Path, m: PluginMeta, namespace: str, *, dry_run: bool = False) -> bool:
    """Copy a plugin's runtime package into its skill's ``scripts/_vendor``.

    Only applies to plugins that declare a ``[vendor]`` table (markdown-only
    plugins skip this and return ``False``). ``namespace`` is the Python package
    namespace shared by the repo ``src/<namespace>/`` and the vendored
    ``_vendor/<namespace>/`` so launchers import the same path either way. The
    whole package tree (including subpackages) is mirrored; stale files and empty
    directories are pruned so the vendored copy always matches the source.
    """
    v = m.vendor
    if not v:
        return False
    if not namespace:
        raise ValueError(
            f"plugin {m.name!r} declares [vendor] but harness.toml sets no vendor_namespace"
        )
    package = v["package"]
    src_pkg = root / "src" / namespace / package
    src_files = {p.relative_to(src_pkg) for p in src_pkg.rglob("*.py")}
    if not src_files:
        raise ValueError(
            f"plugin {m.name!r}: vendor source src/{namespace}/{package} is missing or has no .py files"
        )

    vendor_base = _vendor_dir(m, namespace)
    dest_pkg = vendor_base / package
    changed = _write_if_changed(vendor_base / "__init__.py", _VENDOR_INIT, dry_run=dry_run)
    for rel in sorted(src_files):
        changed |= _write_if_changed(dest_pkg / rel, (src_pkg / rel).read_text(), dry_run=dry_run)

    if dest_pkg.is_dir():  # prune stale vendored files, then empty dirs
        for existing in sorted(dest_pkg.rglob("*.py")):
            if existing.relative_to(dest_pkg) not in src_files:
                changed = True
                if not dry_run:
                    existing.unlink()
        if not dry_run:
            for d in sorted(dest_pkg.rglob("*"), reverse=True):
                if d.is_dir() and not any(d.iterdir()):
                    d.rmdir()
    return changed


def _prune_orphan_vendors(root: Path, expected: set[Path], *, dry_run: bool) -> bool:
    """Remove ``_vendor/<ns>`` dirs no current ``[vendor]`` plugin owns.

    Closes the anti-drift hole where dropping a ``[vendor]`` table or renaming a
    skill would otherwise leave stale vendored code that ``--check`` never saw.
    """
    changed = False
    for vd in sorted((root / "plugins").glob("*/skills/*/scripts/_vendor/*")):
        if vd.is_dir() and vd not in expected:
            changed = True
            if not dry_run:
                shutil.rmtree(vd)
    return changed


def write_all(root: Path, *, dry_run: bool = False) -> bool:
    """Render manifests and vendor plugin code. Returns True if anything changed."""
    mkt = load_marketplace_meta(root)
    metas = _discover(root)
    if any(m.vendor for m in metas) and not mkt.vendor_namespace:
        raise ValueError(
            "a plugin declares [vendor] but harness.toml sets no [marketplace].vendor_namespace"
        )

    changed = False
    expected_vendor: set[Path] = set()
    for m in metas:
        assert m.path is not None
        changed |= _write_if_changed(
            m.path / ".claude-plugin" / "plugin.json",
            _dumps(render_claude_plugin(m)),
            dry_run=dry_run,
        )
        changed |= _write_if_changed(
            m.path / ".codex-plugin" / "plugin.json",
            _dumps(render_codex_plugin(m)),
            dry_run=dry_run,
        )
        changed |= vendor_plugin(root, m, mkt.vendor_namespace, dry_run=dry_run)
        if m.vendor:
            expected_vendor.add(_vendor_dir(m, mkt.vendor_namespace))

    changed |= _prune_orphan_vendors(root, expected_vendor, dry_run=dry_run)
    changed |= _write_if_changed(
        root / ".claude-plugin" / "marketplace.json",
        _dumps(render_marketplace(metas, mkt)),
        dry_run=dry_run,
    )
    return changed
