"""Generate Claude + Codex plugin manifests from a single source of truth.

Each plugin owns one ``plugin.meta.toml``; each harness repo owns one
``harness.toml`` describing the marketplace. From these we render:

- the repo-level Claude ``.claude-plugin/marketplace.json`` (lists all plugins),
- each plugin's ``.claude-plugin/plugin.json``,
- each plugin's ``.codex-plugin/plugin.json``,
- each declared plugin-root shared reference, vendored into the citing skill at
  ``skills/<skill>/references/_shared/<name>.md`` (banner + source bytes) so a
  skill folder copied on its own still resolves what it cites.

Per-plugin manifests carry a ``_generated`` marker; the repo-level
``marketplace.json`` is regenerated wholesale (no marker). All generated files
are byte-stable, and a regenerate-and-diff check (``--check``) guarantees they
never drift — including a sweep that prunes orphaned vendored code when a plugin
drops its ``[vendor]`` table or renames its skill.

Extracted and generalized from ``smorin-harness`` so the generator is shared,
never copied. The marketplace identity (name/owner/metadata) is parameterized via
``harness.toml`` instead of being hard-coded to one repo.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

_GEN_NOTE = "GENERATED by harness-kit from plugin.meta.toml / harness.toml — do not edit"


@dataclass(frozen=True)
class PluginMeta:
    name: str
    version: str
    description: str
    author: str = ""
    keywords: list[str] = field(default_factory=list)
    interface: dict = field(default_factory=dict)
    vendor: dict = field(default_factory=dict)
    generated_shared_references: dict = field(default_factory=dict)
    path: Path | None = None


@dataclass(frozen=True)
class MarketplaceMeta:
    name: str
    description: str
    version: str
    owner: dict = field(default_factory=dict)
    vendor_namespace: str = ""


_META_KEYS = {
    "name",
    "version",
    "description",
    "author",
    "keywords",
    "interface",
    "vendor",
    "generated_shared_references",
}
_GSR_KEYS = {"check_freshness"}


def load_meta(meta_path: Path) -> PluginMeta:
    data = tomllib.loads(meta_path.read_text())
    unknown = sorted(set(data) - _META_KEYS)
    if unknown:
        raise ValueError(f"{meta_path}: unknown plugin.meta.toml keys/tables: {unknown}")
    raw_gsr = data.get("generated_shared_references", {})
    if not isinstance(raw_gsr, dict):
        raise ValueError(f"{meta_path}: [generated_shared_references] must be a table")
    gsr = dict(raw_gsr)
    unknown_gsr = sorted(set(gsr) - _GSR_KEYS)
    if unknown_gsr:
        raise ValueError(f"{meta_path}: unknown [generated_shared_references] keys: {unknown_gsr}")
    if "check_freshness" in gsr and not isinstance(gsr["check_freshness"], bool):
        raise ValueError(
            f"{meta_path}: [generated_shared_references] check_freshness must be a boolean"
        )
    return PluginMeta(
        name=data["name"],
        version=data["version"],
        description=data["description"],
        author=data.get("author", ""),
        keywords=list(data.get("keywords", [])),
        interface=dict(data.get("interface", {})),
        vendor=dict(data.get("vendor", {})),
        generated_shared_references=gsr,
        path=meta_path.parent,
    )


def load_marketplace_meta(root: Path) -> MarketplaceMeta:
    data = tomllib.loads((root / "harness.toml").read_text())
    m = data["marketplace"]
    return MarketplaceMeta(
        name=m["name"],
        description=m["description"],
        version=m["version"],
        owner=dict(m.get("owner", {})),
        vendor_namespace=m.get("vendor_namespace", ""),
    )


def render_claude_plugin(m: PluginMeta) -> dict:
    # Claude Code's plugin schema requires author as an object, not a string.
    return {
        "_generated": _GEN_NOTE,
        "name": m.name,
        "version": m.version,
        "description": m.description,
        "author": {"name": m.author} if m.author else {},
        "keywords": m.keywords,
    }


def render_codex_plugin(m: PluginMeta) -> dict:
    interface = {
        "displayName": m.name.replace("-", " ").title(),
        "shortDescription": m.description,
        "longDescription": m.description,
        "category": "Developer Tools",
    }
    interface.update(m.interface)
    return {
        "_generated": _GEN_NOTE,
        "name": m.name,
        "version": m.version,
        "description": m.description,
        "skills": "./skills/",
        "interface": interface,
    }


def render_marketplace(metas: list[PluginMeta], mkt: MarketplaceMeta) -> dict:
    return {
        "name": mkt.name,
        "owner": mkt.owner,
        "metadata": {"description": mkt.description, "version": mkt.version},
        "plugins": [
            {
                "name": m.name,
                "source": f"./plugins/{m.name}",
                "description": m.description,
                "version": m.version,
                "author": m.author,
                "keywords": m.keywords,
            }
            for m in metas
        ],
    }


def _discover(root: Path) -> list[PluginMeta]:
    return [load_meta(p) for p in sorted((root / "plugins").glob("*/plugin.meta.toml"))]


def _dumps(obj: dict) -> str:
    return json.dumps(obj, indent=2) + "\n"


def _write_if_changed(path: Path, content: str, *, dry_run: bool) -> bool:
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return False
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return True


_VENDOR_INIT = '"""Vendored copy — generated by harness-kit; do not edit."""\n'


def _vendor_dir(m: PluginMeta, namespace: str) -> Path:
    """The ``_vendor/<namespace>`` dir a ``[vendor]`` plugin owns."""
    assert m.path is not None
    return m.path / "skills" / m.vendor["skill"] / "scripts" / "_vendor" / namespace


def vendor_plugin(root: Path, m: PluginMeta, namespace: str, *, dry_run: bool = False) -> bool:
    """Copy a plugin's runtime package into its skill's ``scripts/_vendor``.

    Only applies to plugins that declare a ``[vendor]`` table (markdown-only
    plugins skip this and return ``False``). ``namespace`` is the Python package
    namespace shared by the repo ``src/<namespace>/`` and the vendored
    ``_vendor/<namespace>/`` so launchers import the same path either way. The
    whole package tree (including subpackages) is mirrored; stale files and empty
    directories are pruned so the vendored copy always matches the source.
    """
    v = m.vendor
    if not v:
        return False
    if not namespace:
        raise ValueError(
            f"plugin {m.name!r} declares [vendor] but harness.toml sets no vendor_namespace"
        )
    package = v["package"]
    src_pkg = root / "src" / namespace / package
    src_files = {p.relative_to(src_pkg) for p in src_pkg.rglob("*.py")}
    if not src_files:
        raise ValueError(
            f"plugin {m.name!r}: vendor source src/{namespace}/{package} is missing or has no .py files"
        )

    vendor_base = _vendor_dir(m, namespace)
    dest_pkg = vendor_base / package
    changed = _write_if_changed(vendor_base / "__init__.py", _VENDOR_INIT, dry_run=dry_run)
    for rel in sorted(src_files):
        changed |= _write_if_changed(dest_pkg / rel, (src_pkg / rel).read_text(), dry_run=dry_run)

    if dest_pkg.is_dir():  # prune stale vendored files, then empty dirs
        for existing in sorted(dest_pkg.rglob("*.py")):
            if existing.relative_to(dest_pkg) not in src_files:
                changed = True
                if not dry_run:
                    existing.unlink()
        if not dry_run:
            for d in sorted(dest_pkg.rglob("*"), reverse=True):
                if d.is_dir() and not any(d.iterdir()):
                    d.rmdir()
    return changed


_SHARED_BLOCK_RE = re.compile(r"^```harness-kit-shared-references\n(.*?)^```$", re.M | re.S)


_SHARED_BANNER_PREFIX = "<!-- GENERATED by harness-kit from "


def _write_bytes_if_changed(path: Path, content: bytes) -> bool:
    if path.is_symlink():
        path.unlink()  # a symlink is never a valid generated copy; never write through it
    elif path.exists() and path.read_bytes() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return True


def _shared_banner(source_rel: str) -> str:
    return (
        f"{_SHARED_BANNER_PREFIX}{source_rel} — "
        "do not edit; edit that file and run 'harness-kit gen' -->\n\n"
    )


_SHARED_BASENAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*\.md")
_SHARED_CITE_RE = re.compile(r"references/_shared/([A-Za-z0-9][A-Za-z0-9._-]*\.md)")


def _declared_shared_refs(m: PluginMeta, skill_md_path: Path, source_names: set[str]) -> list[str]:
    """Parse and validate one SKILL.md's shared-reference declarations.

    The fenced ``harness-kit-shared-references`` block is the only declaration
    position; entries are exact plugin-root basenames, each paired with at least
    one operational ``references/_shared/<name>`` citation, and every such
    citation must be declared — a cited-but-unserviced path is the silent
    breakage this feature exists to prevent.
    """
    where = f"plugin {m.name!r} skill {skill_md_path.parent.name!r}"
    text = skill_md_path.read_text()
    block = _SHARED_BLOCK_RE.search(text)
    entries = (
        [line.strip() for line in block.group(1).splitlines() if line.strip()] if block else []
    )
    seen: set[str] = set()
    for e in entries:
        if not _SHARED_BASENAME_RE.fullmatch(e):
            raise ValueError(f"{where}: shared-reference entry {e!r} is not a plugin-root basename")
        if e in seen:
            raise ValueError(f"{where}: duplicate shared-reference entry {e!r}")
        seen.add(e)
        if e not in source_names:
            by_fold = {n.lower(): n for n in source_names}
            actual = by_fold.get(e.lower())
            if actual is not None:
                raise ValueError(
                    f"{where}: entry {e!r} is an exact-case mismatch with plugin-root reference {actual!r}"
                )
            raise ValueError(
                f"{where}: entry {e!r} matches no plugin-root reference in references/"
            )
    cited = set(_SHARED_CITE_RE.findall(text))
    for c in sorted(cited - seen):
        raise ValueError(
            f"{where}: references/_shared/{c} is cited but not declared in the "
            "harness-kit-shared-references block"
        )
    for e in entries:
        if e not in cited:
            raise ValueError(
                f"{where}: entry {e!r} is declared but never cited as references/_shared/{e}"
            )
    return entries


def vendor_shared_references(
    root: Path,
    m: PluginMeta,
    expected: set[Path] | None = None,
    *,
    dry_run: bool = False,
) -> bool:
    """Copy declared plugin-root references into each citing skill's ``_shared``.

    Each skill's SKILL.md declares plugin-root reference basenames in a fenced
    ``harness-kit-shared-references`` block; every declared name is rendered to
    ``skills/<skill>/references/_shared/<name>`` as ``banner + source bytes`` so
    a skill folder copied on its own still resolves what it cites. Every
    declared destination is added to ``expected``, which keeps it out of the
    orphan sweep — a declared copy is never prunable.
    """
    assert m.path is not None
    refs_dir = m.path / "references"
    source_names = (
        {p.name for p in refs_dir.iterdir() if p.is_file()} if refs_dir.is_dir() else set()
    )
    check_freshness = m.generated_shared_references.get("check_freshness", True)
    changed = False
    for skill_md_path in sorted(m.path.glob("skills/*/SKILL.md")):
        for name in _declared_shared_refs(m, skill_md_path, source_names):
            src = refs_dir / name
            src_rel = src.relative_to(root).as_posix()
            if src.is_symlink() or not src.resolve().is_relative_to(refs_dir.resolve()):
                raise ValueError(
                    f"plugin {m.name!r}: refusing to vendor {src_rel}: source is a symlink "
                    "or resolves outside the plugin's references directory"
                )
            src_bytes = src.read_bytes()  # bytes end to end: newlines survive verbatim
            if b"../../references/" in src_bytes:
                raise ValueError(
                    f"plugin {m.name!r}: refusing to vendor {src_rel}: source contains "
                    "'../../references/', which escapes a copied skill tree"
                )
            content = _shared_banner(src_rel).encode() + src_bytes
            dest = skill_md_path.parent / "references" / "_shared" / name
            # Parent containment only: a symlinked destination FILE is handled
            # below (check flags it, write replaces it without following it).
            if not dest.parent.resolve().is_relative_to(skill_md_path.parent.resolve()):
                raise ValueError(
                    f"plugin {m.name!r}: refusing to generate "
                    f"{dest.relative_to(root).as_posix()}: a symlinked parent redirects it "
                    "outside the skill directory"
                )
            if expected is not None:
                expected.add(dest)
            if dry_run:
                # The opt-out suppresses only the staleness comparison here; a
                # missing destination fails regardless, and write mode below
                # regenerates unconditionally.
                dest_rel = dest.relative_to(root).as_posix()
                if dest.is_symlink():
                    print(
                        f"harness-kit: symlinked generated reference: {dest_rel}", file=sys.stderr
                    )
                    changed = True
                elif not dest.is_file():
                    print(f"harness-kit: missing generated reference: {dest_rel}", file=sys.stderr)
                    changed = True
                elif check_freshness and dest.read_bytes() != content:
                    print(f"harness-kit: stale generated reference: {dest_rel}", file=sys.stderr)
                    changed = True
            else:
                changed |= _write_bytes_if_changed(dest, content)
    return changed


def _prune_orphan_shared(root: Path, expected: set[Path], *, dry_run: bool) -> bool:
    """Remove banner-owned ``_shared`` copies no current declaration expects.

    Scope is strictly files carrying the generated banner: hand-placed files in
    ``_shared`` are never deleted. Check mode reports without deleting; write
    mode prunes and removes the ``_shared`` dir once empty.
    """
    changed = False
    for f in sorted((root / "plugins").glob("*/skills/*/references/_shared/*")):
        if not f.is_file() or f in expected:
            continue
        # f.parents[2] is the skill dir; never delete through a symlinked
        # references/ or _shared/ that redirects outside the skill tree.
        if not f.resolve().is_relative_to(f.parents[2].resolve()):
            continue
        with f.open("rb") as fh:  # binary: a stray undecodable file must not crash the sweep
            owned = fh.readline().startswith(_SHARED_BANNER_PREFIX.encode())
        if not owned:
            continue
        changed = True
        if dry_run:
            print(
                f"harness-kit: orphaned generated reference: {f.relative_to(root).as_posix()}",
                file=sys.stderr,
            )
        else:
            f.unlink()
            if not any(f.parent.iterdir()):
                f.parent.rmdir()
    return changed


def _prune_orphan_vendors(root: Path, expected: set[Path], *, dry_run: bool) -> bool:
    """Remove ``_vendor/<ns>`` dirs no current ``[vendor]`` plugin owns.

    Closes the anti-drift hole where dropping a ``[vendor]`` table or renaming a
    skill would otherwise leave stale vendored code that ``--check`` never saw.
    """
    changed = False
    for vd in sorted((root / "plugins").glob("*/skills/*/scripts/_vendor/*")):
        if vd.is_dir() and vd not in expected:
            changed = True
            if not dry_run:
                shutil.rmtree(vd)
    return changed


def write_all(root: Path, *, dry_run: bool = False) -> bool:
    """Render manifests and vendor plugin code. Returns True if anything changed."""
    mkt = load_marketplace_meta(root)
    metas = _discover(root)
    if any(m.vendor for m in metas) and not mkt.vendor_namespace:
        raise ValueError(
            "a plugin declares [vendor] but harness.toml sets no [marketplace].vendor_namespace"
        )

    changed = False
    expected_vendor: set[Path] = set()
    expected_shared: set[Path] = set()
    for m in metas:
        assert m.path is not None
        changed |= _write_if_changed(
            m.path / ".claude-plugin" / "plugin.json",
            _dumps(render_claude_plugin(m)),
            dry_run=dry_run,
        )
        changed |= _write_if_changed(
            m.path / ".codex-plugin" / "plugin.json",
            _dumps(render_codex_plugin(m)),
            dry_run=dry_run,
        )
        changed |= vendor_plugin(root, m, mkt.vendor_namespace, dry_run=dry_run)
        changed |= vendor_shared_references(root, m, expected_shared, dry_run=dry_run)
        if m.vendor:
            expected_vendor.add(_vendor_dir(m, mkt.vendor_namespace))

    changed |= _prune_orphan_vendors(root, expected_vendor, dry_run=dry_run)
    changed |= _prune_orphan_shared(root, expected_shared, dry_run=dry_run)
    changed |= _write_if_changed(
        root / ".claude-plugin" / "marketplace.json",
        _dumps(render_marketplace(metas, mkt)),
        dry_run=dry_run,
    )
    return changed
